# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Streaming' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Streaming

  target 'StreamingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StreamingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'Alamofire', '~> 4.5'

end
